[485607]: HW02 step2
crocs-muni/open-source-development-course-hw02-1 pull request #13
Opened 2020-01-30 01:06 UTC by mareksoska22

2020-01-30 01:18 UTC, mareksoska22 commented
Done

2020-01-30 01:22 UTC, mareksoska22 commented
45137c6855113bd29dbba50748c02b6a4959fd4b - Finish the entire implementation with newly added tests
9bd7b73b541e0c521854389e6f37dd7aab1e4330 - Fix travis branch build
36f14f1c4daa5ce4697b4be739c43bdb79467f62 - Fix unit test discovery
d25d97fb40cbd04005aec2d57e5320f0c2793d2c - Add one minor test
ef8d88c68682fbb97f4fc7d893535d9a1e3a97d9 - Implement minor additional tests
3155db002c8355fe8eee4655e64629ed6b4700c0 - Finished new implementation
f1b7c3f7726bf986d3c33640b86a3336d875c3ad - Finish old implementation

2c7f52e971e5be772ce6f51f96836516e7ff124e - Finish whole implementation
26357a1f9564597662115f1622d01e44880b260a - Add Travis build badge
e48d50348593e60ccfe4ed8c8f432233fa2e6c93 - Do minor README update
b7a67bb9cfd733faa5d700c7361f8943f52f33e5 - Update README with vectors operation
e83e82b36eff835aee614281511eb96b0c638c83 - Update travis branch build
7300266b5f58f0060ec0e7680215dd1ff1947dc4 - Fix travis build, update README with implemented operations
ee49117597d400968ef3945dd208efefef3b014f - Do minor changes
3a23f4b24a97e0ca887575e3f6f2e131dbb0144e - Finish tests implementation
28e9f776e6b9f39c5db998cb911875c09d94cfcb - Begin tests implementation
a48e1c264f241f2ecdc4f4f876c2c7e6c9b46c73 - Finish TODO implementation

2020-01-30 09:42 UTC, ph4r05 commented
Almost perfect :)

Check travis tests: https://travis-ci.com/crocs-muni/open-source-development-course-hw02-1/jobs/281733838

0 tests run. 

Hints:

- check what .travis.yml does precisely, execute same commands. Are tests executed?
- inspect PR fixing the problem: crocs-muni/open-source-development-course-hw02-2#1

2020-01-30 09:43 UTC, ph4r05 requested changes
0 tests run, pls fix

2020-01-30 10:17 UTC, mareksoska22 commented
That one was quite tricky :) 
Done the changes.

2020-01-31 13:41 UTC, ph4r05 approved these changes

2020-02-03 11:45 UTC, ph4r05 commented on ossdev/__init__.py
> +        if self.length() < other.length():
not valid vector comparison. Why only by lenght?

2020-03-26 17:11 UTC, ph4r05 commented
Approved, HW done, closing

2020-03-26 17:11 UTC, closed without merging