[485573]: New Vector operations added
crocs-muni/open-source-development-course-hw02-1 pull request #25
Opened 2020-03-19 13:03 UTC by cucak559

2020-03-19 13:13 UTC, cucak559 commented
-- pr1 (commits are sorted from newest to oldest) (new commits)
a7596fc3f0e7bfe29ebafdc728dfae301b7c32ad - Readme updated with new Vector operations
24bf74209a12ed613d479069a0d1465f3e6d1ac4 - Travis build badge
d94cdc5780ca1153e4cebf81716fdd926c2d1086 - Travis build fixed
473244e40d13193068a9e84c6cdbd1d40e64c055 - Tests for added Vector methods
65d7a2e8ab0ba09adf95ee7d301970d4c08480d5 - Implemented Vector methods marked as TODO

--pr1 after squash (new commits)
50679d48af8d07959d7f10820db16179a006277d - Implemented Vector methods marked as TODO

--pr2 (new commits)
d163e24a534dba05018eab3c7806c7f4a8744657 - Remaining Vector methods added
2de8b5428b2c25ee6001b7875c4dd0367de0cc53 - Tests for Vector __and__ method
ec0f0b6bcabf87b91f9221a322c4890a3f7aa540 - Unit tests fixed

--pr2 after squash (new commits)
546802cd3d16e8820f85c82982ea9d73bb4e4350 - Implemented remaining Vector methods marked as TODO

2020-03-26 17:29 UTC, ph4r05 commented
Travis passes but 0 tests is executed, pls fix this.

2020-04-16 08:22 UTC, ph4r05 requested changes
Pls fix the Travis, 0 tests executed

2020-04-16 08:22 UTC, ph4r05 commented on .travis.yml
> +#  - "3.7"
You could have added tests for 3.7, I mean, fix why 3.7 is not working not commenting it out :)

2020-04-20 15:22 UTC, ph4r05 commented
@cucak559 pls squash the commits to one single signed commit. then I can approve and award you HW points. Pls tag me in comment here when you are done. Thx

2020-04-20 16:17 UTC, cucak559 commented
@ph4r05 Commits squashed

2020-04-20 17:17 UTC, ph4r05 approved these changes

2022-02-24 10:54 UTC, closed without merging